### ISSUE TITLE
Kanbanboard Group Project

### ISSUE THREAD

**Issue by Carshy** [Carshy/movie-capstone-api#21]
https://github.com/Carshy/kanbanboard-group-project/projects/1

We are a team of two members: 
1. Sharon Odhiambo
2. Collins Musoko.

**Comment by julie-ify** [comment]
## Hi @Carshy and @sharon-odhiambo,

Good job so far! 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments here 👇 ._

- [ ] Kindly assign tasks to team members. You should see a circle with the user's avatar on each card when you assign tasks to team members. See the example below:

<img width="274" alt="chrome_T4ZDfx6UTw" src="https://user-images.githubusercontent.com/81468675/182176542-a16bec8e-4544-40a3-835c-e146f1b05545.png">


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Carshy** [comment]
Changes made as requested. @julie-ify thanks for the review

**Comment by FrederickMih** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
